"""
CodeForge Mock Provider - Agent OS
==================================
Mock LLM Provider للاختبار
- استجابات متوقعة قابلة للاختبار (Deterministic)
- قابل للتوسعة بأنماط جديدة
- يسمح باختبار المنصة بدون API Key
"""

import re
from typing import Dict, List, Optional
from dataclasses import dataclass, field

from src.model_provider.base import BaseProvider, ProviderConfig


@dataclass
class MockResponse:
    """استجابة mock"""
    prompt_pattern: str
    response: str
    priority: int = 0


class MockProvider(BaseProvider):
    """
    Mock LLM Provider
    
    Usage:
        from src.model_provider import provider_registry
        
        provider_registry.set_active("mock")
        result = provider_registry.generate("اكتب Hello World")
    """
    
    def __init__(self):
        self._config = ProviderConfig(name="mock")
        self._responses: List[MockResponse] = []
        self._register_default_responses()
    
    @property
    def name(self) -> str:
        return "mock"
    
    @property
    def configured(self) -> bool:
        # Mock لا يحتاج API key
        return True
    
    def _register_default_responses(self):
        """تسجيل الاستجابات الافتراضية"""
        defaults = [
            MockResponse(
                prompt_pattern=r"(?i)hello|مرحبا|اهلا",
                response="Hello! I'm CodeForge AI Assistant. How can I help you today?",
            ),
            MockResponse(
                prompt_pattern=r"(?i)create.*file|إنشاء.*ملف",
                response="""```python
# new_file.py
def main():
    print("Hello, World!")

if __name__ == "__main__":
    main()
```""",
            ),
            MockResponse(
                prompt_pattern=r"(?i)html|صفحة.*هبوط|landing",
                response="""```html
<!DOCTYPE html>
<html>
<head>
    <title>My Landing Page</title>
</head>
<body>
    <h1>Welcome!</h1>
    <p>This is a landing page.</p>
</body>
</html>```""",
            ),
            MockResponse(
                prompt_pattern=r"(?i)readme|README",
                response="""# Project Name\n\n## Description\nThis is a sample project.\n\n## Installation\n```bash\npip install -r requirements.txt\n```\n\n## Usage\n```python\npython main.py\n```""",
            ),
            MockResponse(
                prompt_pattern=r"(?i)summarize|تلخيص",
                response="""## Project Summary\n\nThis is a Python project that demonstrates basic functionality.\n\n- **Status**: Active\n- **Files**: 5\n- **Language**: Python\n- **Framework**: Flask""",
            ),
            MockResponse(
                prompt_pattern=r"(?i)explain|شرح",
                response="""## Code Explanation\n\nThis code defines a simple function that prints a greeting message.\n\n1. The function `main()` is defined\n2. It prints "Hello, World!"\n3. The `if __name__ == "__main__"` block ensures the code only runs when executed directly""",
            ),
            MockResponse(
                prompt_pattern=r"(?i)test|اختبار",
                response="""```python
import pytest

def test_example():
    assert True == True
```""",
            ),
            MockResponse(
                prompt_pattern=r"(?i)api|endpoint",
                response="""```python
from flask import Flask, jsonify

app = Flask(__name__)

@app.route("/api/hello")
def hello():
    return jsonify({"message": "Hello!"})
```""",
            ),
        ]
        
        for r in defaults:
            self._responses.append(r)
    
    def add_response(self, pattern: str, response: str, priority: int = 0):
        """إضافة استجابة مخصصة"""
        self._responses.append(MockResponse(pattern, response, priority))
    
    def generate(self, prompt: str, **kwargs) -> str:
        """توليد استجابة"""
        # ترتيب حسب الأولوية
        sorted_responses = sorted(self._responses, key=lambda x: x.priority, reverse=True)
        
        for mock_response in sorted_responses:
            if re.search(mock_response.prompt_pattern, prompt):
                return mock_response.response
        
        # استجابة افتراضية
        return f"""# Response for: {prompt[:50]}...

This is a mock response from MockProvider.

## Generated Content

```python
# Generated based on your request
def generated_function():
    \"\"\"Generated by CodeForge AI\"\"\"
    pass
```

## Next Steps

1. Review the generated code
2. Test it in your project
3. Commit the changes
"""
    
    def test_connection(self) -> bool:
        """فحص الاتصال - Mock دائماً يعمل"""
        return True


# ============================================================
# Default Instance
# ============================================================

mock_provider = MockProvider()
